AppBundle\Entity\Card:
    type: entity
    table: card
    manyToOne:
        pack:
            targetEntity: Pack
            inversedBy: cards
            joinColumn:
                name: pack_id
                referencedColumnName: id
        type:
            targetEntity: Type
            inversedBy: cards
            joinColumn:
                name: type_id
                referencedColumnName: id
        faction:
            targetEntity: Faction
            inversedBy: cards
            joinColumn:
                name: faction_id
                referencedColumnName: id
    oneToMany:
        reviews:
            targetEntity: Review
            orderBy: {'dateCreation':'DESC'}
            mappedBy: card
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        position:
            type: smallint
            nullable: false
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
        cost:
            type: smallint
            nullable: true
        text:
            type: text
            nullable: true
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        quantity:
            type: smallint
            nullable: false
        income:
            type: smallint
            nullable: true
        initiative:
            type: smallint
            nullable: true
        claim:
            type: smallint
            nullable: true
        reserve:
            type: smallint
            nullable: true
        deckLimit:
            type: smallint
            nullable: true
            column: deck_limit
        strength:
            type: smallint
            nullable: true
        traits:
            type: string
            length: 255
            nullable: true
        flavor:
            type: text
            nullable: true
        illustrator:
            type: string
            length: 255
            nullable: true
        isUnique:
            type: boolean
            nullable: false
            column: is_unique
        isLoyal:
            type: boolean
            nullable: false
            column: is_loyal
        isMilitary:
            type: boolean
            nullable: false
            column: is_military
        isIntrigue:
            type: boolean
            nullable: false
            column: is_intrigue
        isPower:
            type: boolean
            nullable: false
            column: is_power
        octgnId:
            type: string
            nullable: true
            column: octgn_id
    uniqueConstraints:
        card_code_idx:
            columns: [ code ]
